#!/bin/zsh

LOG_FILE="/var/log/download_watcher.log"
STATE_FILE="/tmp/last_download_state.txt"

download() {
    SCRIPT_PATH="$SCRIPTS_DIRECTORY/downloader.py"

    if [ ! -f "$SCRIPT_PATH" ]; then
        echo "Could not find $SCRIPT_PATH."
        return
    fi

    if [ -n "$VENV_PATH" ]; then
        source $VENV_PATH/bin/activate
    fi

    python3 $SCRIPT_PATH "$@"

    # Deactivate the virtual environment properly
    if [ -n "$VIRTUAL_ENV" ]; then
        deactivate
    fi
}

create_file() {
    file_path="$1"

    if [ ! -f "$file_path" ]; then
        touch "$file_path"
        chmod 666 "$file_path"
        sudo chown $(whoami):$(whoami) "$file_path"
    fi
}

# ensure files exist
create_file "$DOWNLOADS_PATH"
create_file "$LOG_FILE"
create_file "$STATE_FILE"

# create initial state
cp "$DOWNLOADS_PATH" "$STATE_FILE"

while true; do
    inotifywait -e modify "$DOWNLOADS_PATH"

    if [ ! -s "$DOWNLOADS_PATH" ]; then
        echo "$(date): File was modified but is empty, skipping." >>"$LOG_FILE"
        cp "$DOWNLOADS_PATH" "$STATE_FILE"
        continue
    fi

    echo "$(date): File changed - $DOWNLOADS_PATH" >>"$LOG_FILE"

    # changed lines in downloads.txt
    NEW_LINES=$(comm -13 <(sort "$STATE_FILE") <(sort "$DOWNLOADS_PATH"))

    while IFS= read -r line; do
        if [[ -n "$line" ]]; then
            echo "$(date): Running download on: $line $DOWNLOADS_PATH" >>"$LOG_FILE"
            download "$line"
        fi
    done <<<"$NEW_LINES"

    cp "$DOWNLOADS_PATH" "$STATE_FILE"
done
