#!/bin/zsh

HISTORY_FILE="$HOME/.zsh_history"

if [[ -z "$1" ]]; then
    depth=2
else
    depth=$1
fi

last_cmd=$(
    tail -n $depth $HISTORY_FILE | head -n 1
)
echo $last_cmd
echo "Last command: '$last_cmd'" >>/tmp/cpout_debug.log

if [[ -z "$last_cmd" ]]; then
    echo "No previous command found."
    exit 1
fi

output=$(eval "$last_cmd" 2>&1)
echo "$output" | pbcopy

echo "Last command's output copied to clipboard."
