#!/bin/bash

if [ -z "$KIWIX_HOST" ]; then
    KIWIX_HOST=$(hostname -I | awk '{print $1}')
fi

if [ -z "$KIWIX_PATH" ]; then
    KIWIX_PATH="/mnt/HOME/kiwix"
fi

if [ -z "$KIWIX_PORT" ]; then
    KIWIX_PORT="8080"
fi

exec /usr/bin/kiwix-serve --port="$KIWIX_PORT" --host="$KIWIX_HOST" "$KIWIX_PATH"
