#!/bin/bash

# find all .conf files
conf_files_dir="$GIT_DOTFILES_DIRECTORY/linux/.services/services"

for conf in "$conf_files_dir"/*.conf; do

    filename="$(basename "$conf")"
    dest_conf="/etc/default/$filename"
    envsubst <"$conf" >"$dest_conf"
    echo "Generated and copied $filename to $dest_conf."
done
