#!/bin/bash

# find all .conf files
conf_files_dir="$GIT_DOTFILES_DIRECTORY/linux/.services/services"
source "~/.zshrc"
source "~/.bashrc"

for conf in "$conf_files_dir"/*.conf; do

    filename="$(basename "$conf")"
    dest_conf="/etc/default/$filename"

    envsubst <"$conf" >"$dest_conf"
    echo "Generated and copied $filename to $dest_conf. $DOWNLOADS_PATH" >/tmp/downloads_log.txt

    echo "[DEBUG] Env before envsubst:" >/tmp/envsubst_debug.log
    env >>/tmp/envsubst_debug.log

    echo "[DEBUG] $(date): Substitution result:" >>/tmp/envsubst_debug.log
    envsubst <"$conf" >>/tmp/envsubst_debug.log
done
