#!/bin/bash

# find all .conf files
conf_files_dir="$GIT_DOTFILES_DIRECTORY/linux/.services/services"

for conf in "$conf_files_dir"/*.conf; do

    filename="$(basename "$conf")"
    envsubst <"$conf" >"/etc/default/$filename"
    echo "Generated and copied $filename to $dest_config_directory."
done

echo "Reloading systemd daemon..."
sudo systemctl daemon-reload
