# colors
export WHITE=0xffffffff

# sketchybar
export SKETCHYBAR_PRIMARY_COLOR=0xFF140C42
export SKETCHYBAR_SECONDARY_COLOR=0xFF2b1c84
export SKETCHYBAR_ACCENT_COLOR=0xFFeb46f9

export PRIMARY_COLOR=0x140C42
export SECONDARY_COLOR=0x2b1c84
export ACCENT_COLOR=0xeb46f9

export SKETCHYBAR_FONT_FAMILY="SF Pro"
export SKETCHYBAR_FONT_TYPEFACE="Bold"
export SKETCHYBAR_FONT_SIZE="16.0"
export SKETCHYBAR_FONT="$SKETCHYBAR_FONT_FAMILY:$SKETCHYBAR_FONT_TYPEFACE:$SKETCHYBAR_FONT_SIZE"
