#!/bin/bash
source "$HOME/.config/themes/theme.sh"

options=(
	style=round
	width=$BORDER_WIDTH
	hidpi=off
	active_color=$BORDER_ACTIVE_COLOR
	inactive_color=$BORDER_INACTIVE_COLOR
)

borders "${options[@]}"
